### PR TITLE
Documentation: Enable application as a service for systemd-based Linux systems

### PR DESCRIPTION
**Pull request by maxime-roy**
Hi ! 

First of all, thanks for working on that project. It's really a helpful tool to use!

I took some notes about the steps I've followed to make the application run as a service on my Raspberry Pi. I figured it could maybe help someone at some point.

Let me know if you have any questions!

Kind regards,

### CODE REVIEW

**Comment by maxime-roy** [comment]
If you think that this content should be in the wiki, don't hesitate to put that there ! 

I've tried to figure if there was some ways to fork the wiki content and then submit some modifications but without success.

**Comment by taburineagle** [comment]
Hello @maxime-roy - thank you very much for the additions!  That's very helpful - I was planning on going that route eventually, as I originally envisioned NeewerLite-Python as a script a Pi could use in tandem with a motion-sensor camera enclosure system I wrote.  I tested everything out with a Pi that I had sitting around, and it worked great, except for a few things -

- `pip` didn't work for me because we're talking Python 3, and pip itself is (I _think_ anyway) for Python 2, but Python 3's `pip3` did, so I might change that in the how-to.

- I know Markdown properly re-numbers the lists in the how-to when it renders them, but I might change them to a numerical order in the .md code itself (in case someone's just looking at the raw version of it and sees the 1. 1. 1. numeration for each step - I was actually confused about that myself at first, but noticed Markdown did render them in the right order when it rendered the file!) - I'm not as well versed on Markdown, so I might be wrong with this.

- Downloading `https://github.com/taburineagle/NeewerLite-Python/archive/refs/tags/0.10.zip` won't get you the `/opt/NeewerLite-Python/systemd/neewerlite-python.service` file, as it's not part of that package (the how-to later suggests editing that file, but just downloading that particular .zip file won't include it, so editing the file will just open up a new blank file) - so I might push a more up-to-date release that includes that file first, and then point the download to that path.

- Making a note that using `sudo systemctl enable neewerlite-python.service` will also start the script as a daemon when the Pi boots up (services always do that, but just to make it clear to someone that might not know that)

- A little tiny annoying issue, but still an issue (this is with the Pi itself, not the pull request!) - `pi` as a user (at least not on my system) can't properly use Bluetooth unless they're also added to the bluetooth group, so everything installs correctly, but NeewerLite-Python can't interact with anything out of the box - so if that's an issue, adding

    `sudo usermod -G bluetooth -a pi`

    And then checking the Pi to make sure the inclusion worked with,

    `cat /etc/group | grep bluetooth`

When I add the `neewerlite-python.service` file to the main package and re-release a new version, I'll merge the PR and update the download link in the how-to!

**Comment by maxime-roy** [comment]
Regarding pip, I confirm that with RasPi OS 64bit bullseye, `pip` is set as an alias to pip3 (or at least pointing to the same executable). 
image

About the numbering, I can change it to sequential numbers :) . While doing internal documentation at my day job, we prefer to use the numbering as I did since it's easier to insert a step in the doc without manually renumber everything. But the documentation here is much smaller so it's less of a problem. I'll also add the requested details regarding the fact that enabling the service will start the script as a daemon. 

And about the pi, strangely enough, I didn't have to add my user to the bluetooth group. But I was able to list/link the lights and use them. I think it could be related to some non-standard/background stuff that Raspberry PI OS set to make things easier. 

Also, if you want, I could create a dockerfile / docker container for the application.

**Comment by taburineagle** [comment]
Got you, got you - I _think_ the reason I may have had the issues with `pip` and the Bluetooth group may have come from me using an outdated version of the Raspberry Pi OS (ha, I think I was actually using Raspbian - to test everything, I did just pull a Pi from a project I was running a few years back, so I'm a few steps behind in updates there :)) - I should flash a SD card with Bullseye and see if those issues are still there.  Everything else looks great!  I did move one small section (the Bluetooth troubleshooting section) to its own 4-step section, because that might be a "your mileage may vary" type of issue (it may just be because mine is out of date).

A docker container would be great, but I'm not at all familiar with Docker myself yet - I know it's used to distribute all kinds of software, but I've never used it myself.  Ha, that's definitely something I need to familiarize myself with!

**Comment by maxime-roy** [comment]
>I did move one small section (the Bluetooth troubleshooting section) to its own 4-step section, because that might be a "your mileage may vary" type of issue (it may just be because mine is out of date).

That's all right, if the information is there, then there's nothing to worry about :)
 
> A docker container would be great, but I'm not at all familiar with Docker myself yet - I know it's used to distribute all kinds of software, but I've never used it myself. Ha, that's definitely something I need to familiarize myself with!

All right ! Then I'll get to create the image, the documentation and the related CI/CD stuff with Github actions on my end when I'll have some free time. I'm more used to use Azure DevOps or ConcourseCI to automate build and deployments, but it shouldn't be that hard to transfer that knowledge to Github Actions :) .

**Comment by taburineagle** [comment]
Ah, excellent - thank you!  I still want to get a few things sorted on my end, and then I'll merge the PR - I'm kind of in and out during the weekend.  I'm also working on a lot of HTTP improvements for 0.11, including making the GUI custom presets available to the HTTP server as well, so when I finish and release that (most _likely_ some time during the next week), I'll change the download link to point to that release.

**Comment by maxime-roy** [comment]
Perfect ! Thanks! 

And if I may suggest something for the 0.11 release, if you have the presets made in a persistent file, can you have the "configuration" files in a folder ? That way, it'll be easy to keep the persistent data between application upgrades with Docker by mapping (doing a `mount --bind`) of that folder to the host hosting the container.   

In a non-containerized setup, it could allow hosting the "config files" on an other drive easily.

**Comment by taburineagle** [comment]
Got you - the custom presets are actually saved in a `light_prefs` folder, the only preference file that isn't is the main program preferences file, but that can be changed.  That should work - or I'm guessing a `light_prefs` folder can be bound to the physical `light_prefs` path in the docker image to replace it - ha, but I might be wrong on that.

**Comment by fribse** [comment]
Great work @maxime-roy and @taburineagle , sounds very promising!

**Comment by taburineagle** [comment]
Thanks Kenneth!  OK, I've merged the use_preset HTTP work back into main, so I'm going to push a new 0.11 release and include this PR in it!

**Pull request merged**
