### PR TITLE
1-5-22 - Allow HTTP CORS

### PR DESCRIPTION
**Pull request by FilipChalupa**
Allows request to be made from web browser using javascript `fetch` function. By that a website on other domain can be made which will send api requests when for example user clicks on a button.

### Before

image

image

While the light stays on. 😢

### After

image

image

And the light actually turns off. 🎉

### CODE REVIEW

**Comment by taburineagle** [comment]
Hi @FilipChalupa - thank you for the contribution!  I tested this in Firefox and Chrome - Firefox seemed to have no issue with the request after the addition using fetch, but Chrome still tossed an error in my limited tests.  Everything looks good though, so I will merge.

**Comment by FilipChalupa** [comment]
To be honest I've tested Chromium based browser (MS Edge) only without any issues. I will try to fix the error you've encountered once it happens to me too.

Thank you very much for the merge and the whole repo in general. 🙂

**Comment by FilipChalupa** [comment]
I've tried it from https://example.com/. The website you are trying to test it with has set to itself [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) which limits what can be done in case some "bad" third party library would try to do something malicious.

CORS sets how other websites can make requests to me.
CSP sets where I can make requests to others.

**Comment by taburineagle** [comment]
Ah, got you - yeah, I'm completely new to CORS actually, so I'm probably testing it wrong :)  I was only using the browser's console, but not coming from a different origin point.

**Pull request merged**
